theme: jekyll-theme-minimal
title: Petrova Oleksandra â€” SysAdmin Engineer | Linux, Azure, Docker, CI/CD
logo: image 3.png
description: Passionate about DevOps, automation, and continuous learning, seeking opportunities to grow under mentorship and contribute to production-ready infrastructure.
author: Oleksandra P.
email: pet.85saf@gmail.com
phone: +380950231078
location: Kyiv, Ukraine
linkedin: https://www.linkedin.com/in/oleksandra-petrova-213909356/
show_downloads: true
google_analytics:

